name: fastapi-github-actions-test

on:
  push:
    branches: [task8-ci-cd]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: pytest .

      - name: Docker login
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Docker build
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/jukov-task8:latest

      - name: Docker push
        run: docker push ${{secrets.DOCKER_USER}}/jukov-task8:latest

      - name: Change permissions
        run: chmod 777 docker-compose.yml

      - uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: './docker-compose.yml'
          remote: '~/Sites/jukov-task8'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
          host: ${{secrets.HOST}}                                      # Remote server address - REQUIRED true
          port: ${{secrets.PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
          user: ${{secrets.USERNAME}}                                      # Remote server user - REQUIRED true
          password: ${{secrets.PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key"
          post_upload: |
            cd ~/Sites/jukov-task8 && 
            docker-compose up --pull -d  # Command to run via ssh after scp upload - REQUIRED false